spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    mysql:
      url: jdbc:mysql://localhost:3306/testdb_mysql
      username : root
      password : password
      driver-class-name: com.mysql.cj.jdbc.Driver

    postgres:
      url: jdbc:postgresql://localhost:5432/testdb_postgres
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver